# Generated by Django 6.1 on 2026-08-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_vehiculo", models.CharField(max_length=120, unique=True)),
                ("plate", models.CharField(max_length=20, unique=True)),
                ("brand", models.CharField(max_length=120)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Alquiler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_alquiler", models.CharField(max_length=120, unique=True)),
                ("customer_name", models.CharField(max_length=120)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(max_length=20, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "vehiculo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alquileres",
                        to="catalog.vehiculo",
                    ),
                ),
            ],
        ),
    ]
